// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

#ifndef PROTOBUF_common_2eproto__INCLUDED
#define PROTOBUF_common_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace message {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_common_2eproto();
void protobuf_AssignDesc_common_2eproto();
void protobuf_ShutdownFile_common_2eproto();

class MsgObjConfig;
class MsgDropBoxConfig;
class MsgIntPair;
class MsgHeroData;
class MsgTaskConditionInfo;
class MsgTaskConfigInfo;
class MsgShopConfigInfo;
class MsgTaskInfo;
class MsgChapterConfigInfo;
class MsgGoldShopConfigInfo;

enum SubType {
  DEFAULT = 0,
  MONSTER = 1,
  INTERACTIVE = 2
};
bool SubType_IsValid(int value);
const SubType SubType_MIN = DEFAULT;
const SubType SubType_MAX = INTERACTIVE;
const int SubType_ARRAYSIZE = SubType_MAX + 1;

const ::google::protobuf::EnumDescriptor* SubType_descriptor();
inline const ::std::string& SubType_Name(SubType value) {
  return ::google::protobuf::internal::NameOfEnum(
    SubType_descriptor(), value);
}
inline bool SubType_Parse(
    const ::std::string& name, SubType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<SubType>(
    SubType_descriptor(), name, value);
}
enum TaskType {
  TaskType_NULL = 0,
  TaskType_KillMonster = 1,
  TaskType_PassGame = 2,
  TaskType_UnKnown = 3,
  TaskType_LimitLevel = 4,
  TaskType_LimitRevive = 5,
  TaskType_LimitTime_KillMonster = 6,
  TaskType_Accumulate_KillMonster = 7
};
bool TaskType_IsValid(int value);
const TaskType TaskType_MIN = TaskType_NULL;
const TaskType TaskType_MAX = TaskType_Accumulate_KillMonster;
const int TaskType_ARRAYSIZE = TaskType_MAX + 1;

const ::google::protobuf::EnumDescriptor* TaskType_descriptor();
inline const ::std::string& TaskType_Name(TaskType value) {
  return ::google::protobuf::internal::NameOfEnum(
    TaskType_descriptor(), value);
}
inline bool TaskType_Parse(
    const ::std::string& name, TaskType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<TaskType>(
    TaskType_descriptor(), name, value);
}
// ===================================================================

class MsgObjConfig : public ::google::protobuf::Message {
 public:
  MsgObjConfig();
  virtual ~MsgObjConfig();

  MsgObjConfig(const MsgObjConfig& from);

  inline MsgObjConfig& operator=(const MsgObjConfig& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MsgObjConfig& default_instance();

  void Swap(MsgObjConfig* other);

  // implements Message ----------------------------------------------

  inline MsgObjConfig* New() const { return New(NULL); }

  MsgObjConfig* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MsgObjConfig& from);
  void MergeFrom(const MsgObjConfig& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(MsgObjConfig* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required .message.SubType type = 1 [default = DEFAULT];
  bool has_type() const;
  void clear_type();
  static const int kTypeFieldNumber = 1;
  ::message::SubType type() const;
  void set_type(::message::SubType value);

  // required int32 id = 2;
  bool has_id() const;
  void clear_id();
  static const int kIdFieldNumber = 2;
  ::google::protobuf::int32 id() const;
  void set_id(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:message.MsgObjConfig)
 private:
  inline void set_has_type();
  inline void clear_has_type();
  inline void set_has_id();
  inline void clear_has_id();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  int type_;
  ::google::protobuf::int32 id_;
  friend void  protobuf_AddDesc_common_2eproto();
  friend void protobuf_AssignDesc_common_2eproto();
  friend void protobuf_ShutdownFile_common_2eproto();

  void InitAsDefaultInstance();
  static MsgObjConfig* default_instance_;
};
// -------------------------------------------------------------------

class MsgDropBoxConfig : public ::google::protobuf::Message {
 public:
  MsgDropBoxConfig();
  virtual ~MsgDropBoxConfig();

  MsgDropBoxConfig(const MsgDropBoxConfig& from);

  inline MsgDropBoxConfig& operator=(const MsgDropBoxConfig& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MsgDropBoxConfig& default_instance();

  void Swap(MsgDropBoxConfig* other);

  // implements Message ----------------------------------------------

  inline MsgDropBoxConfig* New() const { return New(NULL); }

  MsgDropBoxConfig* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MsgDropBoxConfig& from);
  void MergeFrom(const MsgDropBoxConfig& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(MsgDropBoxConfig* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required .message.MsgObjConfig obj = 1;
  bool has_obj() const;
  void clear_obj();
  static const int kObjFieldNumber = 1;
  const ::message::MsgObjConfig& obj() const;
  ::message::MsgObjConfig* mutable_obj();
  ::message::MsgObjConfig* release_obj();
  void set_allocated_obj(::message::MsgObjConfig* obj);

  // required int32 base_gold = 2;
  bool has_base_gold() const;
  void clear_base_gold();
  static const int kBaseGoldFieldNumber = 2;
  ::google::protobuf::int32 base_gold() const;
  void set_base_gold(::google::protobuf::int32 value);

  // required int32 random_gold = 3;
  bool has_random_gold() const;
  void clear_random_gold();
  static const int kRandomGoldFieldNumber = 3;
  ::google::protobuf::int32 random_gold() const;
  void set_random_gold(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:message.MsgDropBoxConfig)
 private:
  inline void set_has_obj();
  inline void clear_has_obj();
  inline void set_has_base_gold();
  inline void clear_has_base_gold();
  inline void set_has_random_gold();
  inline void clear_has_random_gold();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::message::MsgObjConfig* obj_;
  ::google::protobuf::int32 base_gold_;
  ::google::protobuf::int32 random_gold_;
  friend void  protobuf_AddDesc_common_2eproto();
  friend void protobuf_AssignDesc_common_2eproto();
  friend void protobuf_ShutdownFile_common_2eproto();

  void InitAsDefaultInstance();
  static MsgDropBoxConfig* default_instance_;
};
// -------------------------------------------------------------------

class MsgIntPair : public ::google::protobuf::Message {
 public:
  MsgIntPair();
  virtual ~MsgIntPair();

  MsgIntPair(const MsgIntPair& from);

  inline MsgIntPair& operator=(const MsgIntPair& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MsgIntPair& default_instance();

  void Swap(MsgIntPair* other);

  // implements Message ----------------------------------------------

  inline MsgIntPair* New() const { return New(NULL); }

  MsgIntPair* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MsgIntPair& from);
  void MergeFrom(const MsgIntPair& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(MsgIntPair* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 number_1 = 1;
  bool has_number_1() const;
  void clear_number_1();
  static const int kNumber1FieldNumber = 1;
  ::google::protobuf::int32 number_1() const;
  void set_number_1(::google::protobuf::int32 value);

  // required int32 number_2 = 2;
  bool has_number_2() const;
  void clear_number_2();
  static const int kNumber2FieldNumber = 2;
  ::google::protobuf::int32 number_2() const;
  void set_number_2(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:message.MsgIntPair)
 private:
  inline void set_has_number_1();
  inline void clear_has_number_1();
  inline void set_has_number_2();
  inline void clear_has_number_2();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 number_1_;
  ::google::protobuf::int32 number_2_;
  friend void  protobuf_AddDesc_common_2eproto();
  friend void protobuf_AssignDesc_common_2eproto();
  friend void protobuf_ShutdownFile_common_2eproto();

  void InitAsDefaultInstance();
  static MsgIntPair* default_instance_;
};
// -------------------------------------------------------------------

class MsgHeroData : public ::google::protobuf::Message {
 public:
  MsgHeroData();
  virtual ~MsgHeroData();

  MsgHeroData(const MsgHeroData& from);

  inline MsgHeroData& operator=(const MsgHeroData& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MsgHeroData& default_instance();

  void Swap(MsgHeroData* other);

  // implements Message ----------------------------------------------

  inline MsgHeroData* New() const { return New(NULL); }

  MsgHeroData* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MsgHeroData& from);
  void MergeFrom(const MsgHeroData& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(MsgHeroData* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string name = 1;
  bool has_name() const;
  void clear_name();
  static const int kNameFieldNumber = 1;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // required int32 gold = 2;
  bool has_gold() const;
  void clear_gold();
  static const int kGoldFieldNumber = 2;
  ::google::protobuf::int32 gold() const;
  void set_gold(::google::protobuf::int32 value);

  // repeated .message.MsgIntPair records = 3;
  int records_size() const;
  void clear_records();
  static const int kRecordsFieldNumber = 3;
  const ::message::MsgIntPair& records(int index) const;
  ::message::MsgIntPair* mutable_records(int index);
  ::message::MsgIntPair* add_records();
  const ::google::protobuf::RepeatedPtrField< ::message::MsgIntPair >&
      records() const;
  ::google::protobuf::RepeatedPtrField< ::message::MsgIntPair >*
      mutable_records();

  // repeated bool heroes = 4;
  int heroes_size() const;
  void clear_heroes();
  static const int kHeroesFieldNumber = 4;
  bool heroes(int index) const;
  void set_heroes(int index, bool value);
  void add_heroes(bool value);
  const ::google::protobuf::RepeatedField< bool >&
      heroes() const;
  ::google::protobuf::RepeatedField< bool >*
      mutable_heroes();

  // repeated .message.MsgTaskInfo tasks = 5;
  int tasks_size() const;
  void clear_tasks();
  static const int kTasksFieldNumber = 5;
  const ::message::MsgTaskInfo& tasks(int index) const;
  ::message::MsgTaskInfo* mutable_tasks(int index);
  ::message::MsgTaskInfo* add_tasks();
  const ::google::protobuf::RepeatedPtrField< ::message::MsgTaskInfo >&
      tasks() const;
  ::google::protobuf::RepeatedPtrField< ::message::MsgTaskInfo >*
      mutable_tasks();

  // required int32 current_hero = 6;
  bool has_current_hero() const;
  void clear_current_hero();
  static const int kCurrentHeroFieldNumber = 6;
  ::google::protobuf::int32 current_hero() const;
  void set_current_hero(::google::protobuf::int32 value);

  // required int32 complete_task_count = 7;
  bool has_complete_task_count() const;
  void clear_complete_task_count();
  static const int kCompleteTaskCountFieldNumber = 7;
  ::google::protobuf::int32 complete_task_count() const;
  void set_complete_task_count(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:message.MsgHeroData)
 private:
  inline void set_has_name();
  inline void clear_has_name();
  inline void set_has_gold();
  inline void clear_has_gold();
  inline void set_has_current_hero();
  inline void clear_has_current_hero();
  inline void set_has_complete_task_count();
  inline void clear_has_complete_task_count();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::google::protobuf::RepeatedPtrField< ::message::MsgIntPair > records_;
  ::google::protobuf::RepeatedField< bool > heroes_;
  ::google::protobuf::int32 gold_;
  ::google::protobuf::int32 current_hero_;
  ::google::protobuf::RepeatedPtrField< ::message::MsgTaskInfo > tasks_;
  ::google::protobuf::int32 complete_task_count_;
  friend void  protobuf_AddDesc_common_2eproto();
  friend void protobuf_AssignDesc_common_2eproto();
  friend void protobuf_ShutdownFile_common_2eproto();

  void InitAsDefaultInstance();
  static MsgHeroData* default_instance_;
};
// -------------------------------------------------------------------

class MsgTaskConditionInfo : public ::google::protobuf::Message {
 public:
  MsgTaskConditionInfo();
  virtual ~MsgTaskConditionInfo();

  MsgTaskConditionInfo(const MsgTaskConditionInfo& from);

  inline MsgTaskConditionInfo& operator=(const MsgTaskConditionInfo& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MsgTaskConditionInfo& default_instance();

  void Swap(MsgTaskConditionInfo* other);

  // implements Message ----------------------------------------------

  inline MsgTaskConditionInfo* New() const { return New(NULL); }

  MsgTaskConditionInfo* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MsgTaskConditionInfo& from);
  void MergeFrom(const MsgTaskConditionInfo& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(MsgTaskConditionInfo* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required .message.TaskType taskType = 1 [default = TaskType_NULL];
  bool has_tasktype() const;
  void clear_tasktype();
  static const int kTaskTypeFieldNumber = 1;
  ::message::TaskType tasktype() const;
  void set_tasktype(::message::TaskType value);

  // required int32 argument_1 = 2;
  bool has_argument_1() const;
  void clear_argument_1();
  static const int kArgument1FieldNumber = 2;
  ::google::protobuf::int32 argument_1() const;
  void set_argument_1(::google::protobuf::int32 value);

  // required int32 argument_2 = 3;
  bool has_argument_2() const;
  void clear_argument_2();
  static const int kArgument2FieldNumber = 3;
  ::google::protobuf::int32 argument_2() const;
  void set_argument_2(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:message.MsgTaskConditionInfo)
 private:
  inline void set_has_tasktype();
  inline void clear_has_tasktype();
  inline void set_has_argument_1();
  inline void clear_has_argument_1();
  inline void set_has_argument_2();
  inline void clear_has_argument_2();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  int tasktype_;
  ::google::protobuf::int32 argument_1_;
  ::google::protobuf::int32 argument_2_;
  friend void  protobuf_AddDesc_common_2eproto();
  friend void protobuf_AssignDesc_common_2eproto();
  friend void protobuf_ShutdownFile_common_2eproto();

  void InitAsDefaultInstance();
  static MsgTaskConditionInfo* default_instance_;
};
// -------------------------------------------------------------------

class MsgTaskConfigInfo : public ::google::protobuf::Message {
 public:
  MsgTaskConfigInfo();
  virtual ~MsgTaskConfigInfo();

  MsgTaskConfigInfo(const MsgTaskConfigInfo& from);

  inline MsgTaskConfigInfo& operator=(const MsgTaskConfigInfo& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MsgTaskConfigInfo& default_instance();

  void Swap(MsgTaskConfigInfo* other);

  // implements Message ----------------------------------------------

  inline MsgTaskConfigInfo* New() const { return New(NULL); }

  MsgTaskConfigInfo* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MsgTaskConfigInfo& from);
  void MergeFrom(const MsgTaskConfigInfo& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(MsgTaskConfigInfo* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 taskID = 1;
  bool has_taskid() const;
  void clear_taskid();
  static const int kTaskIDFieldNumber = 1;
  ::google::protobuf::int32 taskid() const;
  void set_taskid(::google::protobuf::int32 value);

  // repeated .message.MsgTaskConditionInfo task_condition = 2;
  int task_condition_size() const;
  void clear_task_condition();
  static const int kTaskConditionFieldNumber = 2;
  const ::message::MsgTaskConditionInfo& task_condition(int index) const;
  ::message::MsgTaskConditionInfo* mutable_task_condition(int index);
  ::message::MsgTaskConditionInfo* add_task_condition();
  const ::google::protobuf::RepeatedPtrField< ::message::MsgTaskConditionInfo >&
      task_condition() const;
  ::google::protobuf::RepeatedPtrField< ::message::MsgTaskConditionInfo >*
      mutable_task_condition();

  // required int32 require_time = 3;
  bool has_require_time() const;
  void clear_require_time();
  static const int kRequireTimeFieldNumber = 3;
  ::google::protobuf::int32 require_time() const;
  void set_require_time(::google::protobuf::int32 value);

  // required int32 require_unlock_chapter = 4;
  bool has_require_unlock_chapter() const;
  void clear_require_unlock_chapter();
  static const int kRequireUnlockChapterFieldNumber = 4;
  ::google::protobuf::int32 require_unlock_chapter() const;
  void set_require_unlock_chapter(::google::protobuf::int32 value);

  // required int32 require_unlock_section = 5;
  bool has_require_unlock_section() const;
  void clear_require_unlock_section();
  static const int kRequireUnlockSectionFieldNumber = 5;
  ::google::protobuf::int32 require_unlock_section() const;
  void set_require_unlock_section(::google::protobuf::int32 value);

  // required int32 require_unlock_complete_task_count = 6;
  bool has_require_unlock_complete_task_count() const;
  void clear_require_unlock_complete_task_count();
  static const int kRequireUnlockCompleteTaskCountFieldNumber = 6;
  ::google::protobuf::int32 require_unlock_complete_task_count() const;
  void set_require_unlock_complete_task_count(::google::protobuf::int32 value);

  // required int32 gift_gold = 7;
  bool has_gift_gold() const;
  void clear_gift_gold();
  static const int kGiftGoldFieldNumber = 7;
  ::google::protobuf::int32 gift_gold() const;
  void set_gift_gold(::google::protobuf::int32 value);

  // required string describe = 8;
  bool has_describe() const;
  void clear_describe();
  static const int kDescribeFieldNumber = 8;
  const ::std::string& describe() const;
  void set_describe(const ::std::string& value);
  void set_describe(const char* value);
  void set_describe(const char* value, size_t size);
  ::std::string* mutable_describe();
  ::std::string* release_describe();
  void set_allocated_describe(::std::string* describe);

  // @@protoc_insertion_point(class_scope:message.MsgTaskConfigInfo)
 private:
  inline void set_has_taskid();
  inline void clear_has_taskid();
  inline void set_has_require_time();
  inline void clear_has_require_time();
  inline void set_has_require_unlock_chapter();
  inline void clear_has_require_unlock_chapter();
  inline void set_has_require_unlock_section();
  inline void clear_has_require_unlock_section();
  inline void set_has_require_unlock_complete_task_count();
  inline void clear_has_require_unlock_complete_task_count();
  inline void set_has_gift_gold();
  inline void clear_has_gift_gold();
  inline void set_has_describe();
  inline void clear_has_describe();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::message::MsgTaskConditionInfo > task_condition_;
  ::google::protobuf::int32 taskid_;
  ::google::protobuf::int32 require_time_;
  ::google::protobuf::int32 require_unlock_chapter_;
  ::google::protobuf::int32 require_unlock_section_;
  ::google::protobuf::int32 require_unlock_complete_task_count_;
  ::google::protobuf::int32 gift_gold_;
  ::google::protobuf::internal::ArenaStringPtr describe_;
  friend void  protobuf_AddDesc_common_2eproto();
  friend void protobuf_AssignDesc_common_2eproto();
  friend void protobuf_ShutdownFile_common_2eproto();

  void InitAsDefaultInstance();
  static MsgTaskConfigInfo* default_instance_;
};
// -------------------------------------------------------------------

class MsgShopConfigInfo : public ::google::protobuf::Message {
 public:
  MsgShopConfigInfo();
  virtual ~MsgShopConfigInfo();

  MsgShopConfigInfo(const MsgShopConfigInfo& from);

  inline MsgShopConfigInfo& operator=(const MsgShopConfigInfo& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MsgShopConfigInfo& default_instance();

  void Swap(MsgShopConfigInfo* other);

  // implements Message ----------------------------------------------

  inline MsgShopConfigInfo* New() const { return New(NULL); }

  MsgShopConfigInfo* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MsgShopConfigInfo& from);
  void MergeFrom(const MsgShopConfigInfo& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(MsgShopConfigInfo* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 grid_id = 1;
  bool has_grid_id() const;
  void clear_grid_id();
  static const int kGridIdFieldNumber = 1;
  ::google::protobuf::int32 grid_id() const;
  void set_grid_id(::google::protobuf::int32 value);

  // required int32 hero_id = 2;
  bool has_hero_id() const;
  void clear_hero_id();
  static const int kHeroIdFieldNumber = 2;
  ::google::protobuf::int32 hero_id() const;
  void set_hero_id(::google::protobuf::int32 value);

  // required int32 require_gold = 3;
  bool has_require_gold() const;
  void clear_require_gold();
  static const int kRequireGoldFieldNumber = 3;
  ::google::protobuf::int32 require_gold() const;
  void set_require_gold(::google::protobuf::int32 value);

  // required int32 cheape_gold = 4;
  bool has_cheape_gold() const;
  void clear_cheape_gold();
  static const int kCheapeGoldFieldNumber = 4;
  ::google::protobuf::int32 cheape_gold() const;
  void set_cheape_gold(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:message.MsgShopConfigInfo)
 private:
  inline void set_has_grid_id();
  inline void clear_has_grid_id();
  inline void set_has_hero_id();
  inline void clear_has_hero_id();
  inline void set_has_require_gold();
  inline void clear_has_require_gold();
  inline void set_has_cheape_gold();
  inline void clear_has_cheape_gold();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 grid_id_;
  ::google::protobuf::int32 hero_id_;
  ::google::protobuf::int32 require_gold_;
  ::google::protobuf::int32 cheape_gold_;
  friend void  protobuf_AddDesc_common_2eproto();
  friend void protobuf_AssignDesc_common_2eproto();
  friend void protobuf_ShutdownFile_common_2eproto();

  void InitAsDefaultInstance();
  static MsgShopConfigInfo* default_instance_;
};
// -------------------------------------------------------------------

class MsgTaskInfo : public ::google::protobuf::Message {
 public:
  MsgTaskInfo();
  virtual ~MsgTaskInfo();

  MsgTaskInfo(const MsgTaskInfo& from);

  inline MsgTaskInfo& operator=(const MsgTaskInfo& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MsgTaskInfo& default_instance();

  void Swap(MsgTaskInfo* other);

  // implements Message ----------------------------------------------

  inline MsgTaskInfo* New() const { return New(NULL); }

  MsgTaskInfo* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MsgTaskInfo& from);
  void MergeFrom(const MsgTaskInfo& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(MsgTaskInfo* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 TaskID = 1;
  bool has_taskid() const;
  void clear_taskid();
  static const int kTaskIDFieldNumber = 1;
  ::google::protobuf::int32 taskid() const;
  void set_taskid(::google::protobuf::int32 value);

  // required int32 argument_1 = 2;
  bool has_argument_1() const;
  void clear_argument_1();
  static const int kArgument1FieldNumber = 2;
  ::google::protobuf::int32 argument_1() const;
  void set_argument_1(::google::protobuf::int32 value);

  // required int32 useTime = 3;
  bool has_usetime() const;
  void clear_usetime();
  static const int kUseTimeFieldNumber = 3;
  ::google::protobuf::int32 usetime() const;
  void set_usetime(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:message.MsgTaskInfo)
 private:
  inline void set_has_taskid();
  inline void clear_has_taskid();
  inline void set_has_argument_1();
  inline void clear_has_argument_1();
  inline void set_has_usetime();
  inline void clear_has_usetime();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 taskid_;
  ::google::protobuf::int32 argument_1_;
  ::google::protobuf::int32 usetime_;
  friend void  protobuf_AddDesc_common_2eproto();
  friend void protobuf_AssignDesc_common_2eproto();
  friend void protobuf_ShutdownFile_common_2eproto();

  void InitAsDefaultInstance();
  static MsgTaskInfo* default_instance_;
};
// -------------------------------------------------------------------

class MsgChapterConfigInfo : public ::google::protobuf::Message {
 public:
  MsgChapterConfigInfo();
  virtual ~MsgChapterConfigInfo();

  MsgChapterConfigInfo(const MsgChapterConfigInfo& from);

  inline MsgChapterConfigInfo& operator=(const MsgChapterConfigInfo& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MsgChapterConfigInfo& default_instance();

  void Swap(MsgChapterConfigInfo* other);

  // implements Message ----------------------------------------------

  inline MsgChapterConfigInfo* New() const { return New(NULL); }

  MsgChapterConfigInfo* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MsgChapterConfigInfo& from);
  void MergeFrom(const MsgChapterConfigInfo& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(MsgChapterConfigInfo* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 chapter_id = 1;
  bool has_chapter_id() const;
  void clear_chapter_id();
  static const int kChapterIdFieldNumber = 1;
  ::google::protobuf::int32 chapter_id() const;
  void set_chapter_id(::google::protobuf::int32 value);

  // required int32 required_chapter_id = 2;
  bool has_required_chapter_id() const;
  void clear_required_chapter_id();
  static const int kRequiredChapterIdFieldNumber = 2;
  ::google::protobuf::int32 required_chapter_id() const;
  void set_required_chapter_id(::google::protobuf::int32 value);

  // required int32 required_section_id = 3;
  bool has_required_section_id() const;
  void clear_required_section_id();
  static const int kRequiredSectionIdFieldNumber = 3;
  ::google::protobuf::int32 required_section_id() const;
  void set_required_section_id(::google::protobuf::int32 value);

  // required int32 required_task_complete_count = 4;
  bool has_required_task_complete_count() const;
  void clear_required_task_complete_count();
  static const int kRequiredTaskCompleteCountFieldNumber = 4;
  ::google::protobuf::int32 required_task_complete_count() const;
  void set_required_task_complete_count(::google::protobuf::int32 value);

  // required int32 require_gold = 5;
  bool has_require_gold() const;
  void clear_require_gold();
  static const int kRequireGoldFieldNumber = 5;
  ::google::protobuf::int32 require_gold() const;
  void set_require_gold(::google::protobuf::int32 value);

  // required int32 max_section_count = 6;
  bool has_max_section_count() const;
  void clear_max_section_count();
  static const int kMaxSectionCountFieldNumber = 6;
  ::google::protobuf::int32 max_section_count() const;
  void set_max_section_count(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:message.MsgChapterConfigInfo)
 private:
  inline void set_has_chapter_id();
  inline void clear_has_chapter_id();
  inline void set_has_required_chapter_id();
  inline void clear_has_required_chapter_id();
  inline void set_has_required_section_id();
  inline void clear_has_required_section_id();
  inline void set_has_required_task_complete_count();
  inline void clear_has_required_task_complete_count();
  inline void set_has_require_gold();
  inline void clear_has_require_gold();
  inline void set_has_max_section_count();
  inline void clear_has_max_section_count();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 chapter_id_;
  ::google::protobuf::int32 required_chapter_id_;
  ::google::protobuf::int32 required_section_id_;
  ::google::protobuf::int32 required_task_complete_count_;
  ::google::protobuf::int32 require_gold_;
  ::google::protobuf::int32 max_section_count_;
  friend void  protobuf_AddDesc_common_2eproto();
  friend void protobuf_AssignDesc_common_2eproto();
  friend void protobuf_ShutdownFile_common_2eproto();

  void InitAsDefaultInstance();
  static MsgChapterConfigInfo* default_instance_;
};
// -------------------------------------------------------------------

class MsgGoldShopConfigInfo : public ::google::protobuf::Message {
 public:
  MsgGoldShopConfigInfo();
  virtual ~MsgGoldShopConfigInfo();

  MsgGoldShopConfigInfo(const MsgGoldShopConfigInfo& from);

  inline MsgGoldShopConfigInfo& operator=(const MsgGoldShopConfigInfo& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MsgGoldShopConfigInfo& default_instance();

  void Swap(MsgGoldShopConfigInfo* other);

  // implements Message ----------------------------------------------

  inline MsgGoldShopConfigInfo* New() const { return New(NULL); }

  MsgGoldShopConfigInfo* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MsgGoldShopConfigInfo& from);
  void MergeFrom(const MsgGoldShopConfigInfo& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(MsgGoldShopConfigInfo* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 id = 1;
  bool has_id() const;
  void clear_id();
  static const int kIdFieldNumber = 1;
  ::google::protobuf::int32 id() const;
  void set_id(::google::protobuf::int32 value);

  // required int32 resource_id = 2;
  bool has_resource_id() const;
  void clear_resource_id();
  static const int kResourceIdFieldNumber = 2;
  ::google::protobuf::int32 resource_id() const;
  void set_resource_id(::google::protobuf::int32 value);

  // required int32 gold = 3;
  bool has_gold() const;
  void clear_gold();
  static const int kGoldFieldNumber = 3;
  ::google::protobuf::int32 gold() const;
  void set_gold(::google::protobuf::int32 value);

  // required float money = 4;
  bool has_money() const;
  void clear_money();
  static const int kMoneyFieldNumber = 4;
  float money() const;
  void set_money(float value);

  // required string describe = 5;
  bool has_describe() const;
  void clear_describe();
  static const int kDescribeFieldNumber = 5;
  const ::std::string& describe() const;
  void set_describe(const ::std::string& value);
  void set_describe(const char* value);
  void set_describe(const char* value, size_t size);
  ::std::string* mutable_describe();
  ::std::string* release_describe();
  void set_allocated_describe(::std::string* describe);

  // @@protoc_insertion_point(class_scope:message.MsgGoldShopConfigInfo)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_resource_id();
  inline void clear_has_resource_id();
  inline void set_has_gold();
  inline void clear_has_gold();
  inline void set_has_money();
  inline void clear_has_money();
  inline void set_has_describe();
  inline void clear_has_describe();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 id_;
  ::google::protobuf::int32 resource_id_;
  ::google::protobuf::int32 gold_;
  float money_;
  ::google::protobuf::internal::ArenaStringPtr describe_;
  friend void  protobuf_AddDesc_common_2eproto();
  friend void protobuf_AssignDesc_common_2eproto();
  friend void protobuf_ShutdownFile_common_2eproto();

  void InitAsDefaultInstance();
  static MsgGoldShopConfigInfo* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// MsgObjConfig

// required .message.SubType type = 1 [default = DEFAULT];
inline bool MsgObjConfig::has_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MsgObjConfig::set_has_type() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MsgObjConfig::clear_has_type() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MsgObjConfig::clear_type() {
  type_ = 0;
  clear_has_type();
}
inline ::message::SubType MsgObjConfig::type() const {
  // @@protoc_insertion_point(field_get:message.MsgObjConfig.type)
  return static_cast< ::message::SubType >(type_);
}
inline void MsgObjConfig::set_type(::message::SubType value) {
  assert(::message::SubType_IsValid(value));
  set_has_type();
  type_ = value;
  // @@protoc_insertion_point(field_set:message.MsgObjConfig.type)
}

// required int32 id = 2;
inline bool MsgObjConfig::has_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MsgObjConfig::set_has_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MsgObjConfig::clear_has_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MsgObjConfig::clear_id() {
  id_ = 0;
  clear_has_id();
}
inline ::google::protobuf::int32 MsgObjConfig::id() const {
  // @@protoc_insertion_point(field_get:message.MsgObjConfig.id)
  return id_;
}
inline void MsgObjConfig::set_id(::google::protobuf::int32 value) {
  set_has_id();
  id_ = value;
  // @@protoc_insertion_point(field_set:message.MsgObjConfig.id)
}

// -------------------------------------------------------------------

// MsgDropBoxConfig

// required .message.MsgObjConfig obj = 1;
inline bool MsgDropBoxConfig::has_obj() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MsgDropBoxConfig::set_has_obj() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MsgDropBoxConfig::clear_has_obj() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MsgDropBoxConfig::clear_obj() {
  if (obj_ != NULL) obj_->::message::MsgObjConfig::Clear();
  clear_has_obj();
}
inline const ::message::MsgObjConfig& MsgDropBoxConfig::obj() const {
  // @@protoc_insertion_point(field_get:message.MsgDropBoxConfig.obj)
  return obj_ != NULL ? *obj_ : *default_instance_->obj_;
}
inline ::message::MsgObjConfig* MsgDropBoxConfig::mutable_obj() {
  set_has_obj();
  if (obj_ == NULL) {
    obj_ = new ::message::MsgObjConfig;
  }
  // @@protoc_insertion_point(field_mutable:message.MsgDropBoxConfig.obj)
  return obj_;
}
inline ::message::MsgObjConfig* MsgDropBoxConfig::release_obj() {
  clear_has_obj();
  ::message::MsgObjConfig* temp = obj_;
  obj_ = NULL;
  return temp;
}
inline void MsgDropBoxConfig::set_allocated_obj(::message::MsgObjConfig* obj) {
  delete obj_;
  obj_ = obj;
  if (obj) {
    set_has_obj();
  } else {
    clear_has_obj();
  }
  // @@protoc_insertion_point(field_set_allocated:message.MsgDropBoxConfig.obj)
}

// required int32 base_gold = 2;
inline bool MsgDropBoxConfig::has_base_gold() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MsgDropBoxConfig::set_has_base_gold() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MsgDropBoxConfig::clear_has_base_gold() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MsgDropBoxConfig::clear_base_gold() {
  base_gold_ = 0;
  clear_has_base_gold();
}
inline ::google::protobuf::int32 MsgDropBoxConfig::base_gold() const {
  // @@protoc_insertion_point(field_get:message.MsgDropBoxConfig.base_gold)
  return base_gold_;
}
inline void MsgDropBoxConfig::set_base_gold(::google::protobuf::int32 value) {
  set_has_base_gold();
  base_gold_ = value;
  // @@protoc_insertion_point(field_set:message.MsgDropBoxConfig.base_gold)
}

// required int32 random_gold = 3;
inline bool MsgDropBoxConfig::has_random_gold() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void MsgDropBoxConfig::set_has_random_gold() {
  _has_bits_[0] |= 0x00000004u;
}
inline void MsgDropBoxConfig::clear_has_random_gold() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void MsgDropBoxConfig::clear_random_gold() {
  random_gold_ = 0;
  clear_has_random_gold();
}
inline ::google::protobuf::int32 MsgDropBoxConfig::random_gold() const {
  // @@protoc_insertion_point(field_get:message.MsgDropBoxConfig.random_gold)
  return random_gold_;
}
inline void MsgDropBoxConfig::set_random_gold(::google::protobuf::int32 value) {
  set_has_random_gold();
  random_gold_ = value;
  // @@protoc_insertion_point(field_set:message.MsgDropBoxConfig.random_gold)
}

// -------------------------------------------------------------------

// MsgIntPair

// required int32 number_1 = 1;
inline bool MsgIntPair::has_number_1() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MsgIntPair::set_has_number_1() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MsgIntPair::clear_has_number_1() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MsgIntPair::clear_number_1() {
  number_1_ = 0;
  clear_has_number_1();
}
inline ::google::protobuf::int32 MsgIntPair::number_1() const {
  // @@protoc_insertion_point(field_get:message.MsgIntPair.number_1)
  return number_1_;
}
inline void MsgIntPair::set_number_1(::google::protobuf::int32 value) {
  set_has_number_1();
  number_1_ = value;
  // @@protoc_insertion_point(field_set:message.MsgIntPair.number_1)
}

// required int32 number_2 = 2;
inline bool MsgIntPair::has_number_2() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MsgIntPair::set_has_number_2() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MsgIntPair::clear_has_number_2() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MsgIntPair::clear_number_2() {
  number_2_ = 0;
  clear_has_number_2();
}
inline ::google::protobuf::int32 MsgIntPair::number_2() const {
  // @@protoc_insertion_point(field_get:message.MsgIntPair.number_2)
  return number_2_;
}
inline void MsgIntPair::set_number_2(::google::protobuf::int32 value) {
  set_has_number_2();
  number_2_ = value;
  // @@protoc_insertion_point(field_set:message.MsgIntPair.number_2)
}

// -------------------------------------------------------------------

// MsgHeroData

// required string name = 1;
inline bool MsgHeroData::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MsgHeroData::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MsgHeroData::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MsgHeroData::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_name();
}
inline const ::std::string& MsgHeroData::name() const {
  // @@protoc_insertion_point(field_get:message.MsgHeroData.name)
  return name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void MsgHeroData::set_name(const ::std::string& value) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:message.MsgHeroData.name)
}
inline void MsgHeroData::set_name(const char* value) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:message.MsgHeroData.name)
}
inline void MsgHeroData::set_name(const char* value, size_t size) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:message.MsgHeroData.name)
}
inline ::std::string* MsgHeroData::mutable_name() {
  set_has_name();
  // @@protoc_insertion_point(field_mutable:message.MsgHeroData.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* MsgHeroData::release_name() {
  clear_has_name();
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void MsgHeroData::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    set_has_name();
  } else {
    clear_has_name();
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:message.MsgHeroData.name)
}

// required int32 gold = 2;
inline bool MsgHeroData::has_gold() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MsgHeroData::set_has_gold() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MsgHeroData::clear_has_gold() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MsgHeroData::clear_gold() {
  gold_ = 0;
  clear_has_gold();
}
inline ::google::protobuf::int32 MsgHeroData::gold() const {
  // @@protoc_insertion_point(field_get:message.MsgHeroData.gold)
  return gold_;
}
inline void MsgHeroData::set_gold(::google::protobuf::int32 value) {
  set_has_gold();
  gold_ = value;
  // @@protoc_insertion_point(field_set:message.MsgHeroData.gold)
}

// repeated .message.MsgIntPair records = 3;
inline int MsgHeroData::records_size() const {
  return records_.size();
}
inline void MsgHeroData::clear_records() {
  records_.Clear();
}
inline const ::message::MsgIntPair& MsgHeroData::records(int index) const {
  // @@protoc_insertion_point(field_get:message.MsgHeroData.records)
  return records_.Get(index);
}
inline ::message::MsgIntPair* MsgHeroData::mutable_records(int index) {
  // @@protoc_insertion_point(field_mutable:message.MsgHeroData.records)
  return records_.Mutable(index);
}
inline ::message::MsgIntPair* MsgHeroData::add_records() {
  // @@protoc_insertion_point(field_add:message.MsgHeroData.records)
  return records_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::message::MsgIntPair >&
MsgHeroData::records() const {
  // @@protoc_insertion_point(field_list:message.MsgHeroData.records)
  return records_;
}
inline ::google::protobuf::RepeatedPtrField< ::message::MsgIntPair >*
MsgHeroData::mutable_records() {
  // @@protoc_insertion_point(field_mutable_list:message.MsgHeroData.records)
  return &records_;
}

// repeated bool heroes = 4;
inline int MsgHeroData::heroes_size() const {
  return heroes_.size();
}
inline void MsgHeroData::clear_heroes() {
  heroes_.Clear();
}
inline bool MsgHeroData::heroes(int index) const {
  // @@protoc_insertion_point(field_get:message.MsgHeroData.heroes)
  return heroes_.Get(index);
}
inline void MsgHeroData::set_heroes(int index, bool value) {
  heroes_.Set(index, value);
  // @@protoc_insertion_point(field_set:message.MsgHeroData.heroes)
}
inline void MsgHeroData::add_heroes(bool value) {
  heroes_.Add(value);
  // @@protoc_insertion_point(field_add:message.MsgHeroData.heroes)
}
inline const ::google::protobuf::RepeatedField< bool >&
MsgHeroData::heroes() const {
  // @@protoc_insertion_point(field_list:message.MsgHeroData.heroes)
  return heroes_;
}
inline ::google::protobuf::RepeatedField< bool >*
MsgHeroData::mutable_heroes() {
  // @@protoc_insertion_point(field_mutable_list:message.MsgHeroData.heroes)
  return &heroes_;
}

// repeated .message.MsgTaskInfo tasks = 5;
inline int MsgHeroData::tasks_size() const {
  return tasks_.size();
}
inline void MsgHeroData::clear_tasks() {
  tasks_.Clear();
}
inline const ::message::MsgTaskInfo& MsgHeroData::tasks(int index) const {
  // @@protoc_insertion_point(field_get:message.MsgHeroData.tasks)
  return tasks_.Get(index);
}
inline ::message::MsgTaskInfo* MsgHeroData::mutable_tasks(int index) {
  // @@protoc_insertion_point(field_mutable:message.MsgHeroData.tasks)
  return tasks_.Mutable(index);
}
inline ::message::MsgTaskInfo* MsgHeroData::add_tasks() {
  // @@protoc_insertion_point(field_add:message.MsgHeroData.tasks)
  return tasks_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::message::MsgTaskInfo >&
MsgHeroData::tasks() const {
  // @@protoc_insertion_point(field_list:message.MsgHeroData.tasks)
  return tasks_;
}
inline ::google::protobuf::RepeatedPtrField< ::message::MsgTaskInfo >*
MsgHeroData::mutable_tasks() {
  // @@protoc_insertion_point(field_mutable_list:message.MsgHeroData.tasks)
  return &tasks_;
}

// required int32 current_hero = 6;
inline bool MsgHeroData::has_current_hero() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void MsgHeroData::set_has_current_hero() {
  _has_bits_[0] |= 0x00000020u;
}
inline void MsgHeroData::clear_has_current_hero() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void MsgHeroData::clear_current_hero() {
  current_hero_ = 0;
  clear_has_current_hero();
}
inline ::google::protobuf::int32 MsgHeroData::current_hero() const {
  // @@protoc_insertion_point(field_get:message.MsgHeroData.current_hero)
  return current_hero_;
}
inline void MsgHeroData::set_current_hero(::google::protobuf::int32 value) {
  set_has_current_hero();
  current_hero_ = value;
  // @@protoc_insertion_point(field_set:message.MsgHeroData.current_hero)
}

// required int32 complete_task_count = 7;
inline bool MsgHeroData::has_complete_task_count() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void MsgHeroData::set_has_complete_task_count() {
  _has_bits_[0] |= 0x00000040u;
}
inline void MsgHeroData::clear_has_complete_task_count() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void MsgHeroData::clear_complete_task_count() {
  complete_task_count_ = 0;
  clear_has_complete_task_count();
}
inline ::google::protobuf::int32 MsgHeroData::complete_task_count() const {
  // @@protoc_insertion_point(field_get:message.MsgHeroData.complete_task_count)
  return complete_task_count_;
}
inline void MsgHeroData::set_complete_task_count(::google::protobuf::int32 value) {
  set_has_complete_task_count();
  complete_task_count_ = value;
  // @@protoc_insertion_point(field_set:message.MsgHeroData.complete_task_count)
}

// -------------------------------------------------------------------

// MsgTaskConditionInfo

// required .message.TaskType taskType = 1 [default = TaskType_NULL];
inline bool MsgTaskConditionInfo::has_tasktype() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MsgTaskConditionInfo::set_has_tasktype() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MsgTaskConditionInfo::clear_has_tasktype() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MsgTaskConditionInfo::clear_tasktype() {
  tasktype_ = 0;
  clear_has_tasktype();
}
inline ::message::TaskType MsgTaskConditionInfo::tasktype() const {
  // @@protoc_insertion_point(field_get:message.MsgTaskConditionInfo.taskType)
  return static_cast< ::message::TaskType >(tasktype_);
}
inline void MsgTaskConditionInfo::set_tasktype(::message::TaskType value) {
  assert(::message::TaskType_IsValid(value));
  set_has_tasktype();
  tasktype_ = value;
  // @@protoc_insertion_point(field_set:message.MsgTaskConditionInfo.taskType)
}

// required int32 argument_1 = 2;
inline bool MsgTaskConditionInfo::has_argument_1() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MsgTaskConditionInfo::set_has_argument_1() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MsgTaskConditionInfo::clear_has_argument_1() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MsgTaskConditionInfo::clear_argument_1() {
  argument_1_ = 0;
  clear_has_argument_1();
}
inline ::google::protobuf::int32 MsgTaskConditionInfo::argument_1() const {
  // @@protoc_insertion_point(field_get:message.MsgTaskConditionInfo.argument_1)
  return argument_1_;
}
inline void MsgTaskConditionInfo::set_argument_1(::google::protobuf::int32 value) {
  set_has_argument_1();
  argument_1_ = value;
  // @@protoc_insertion_point(field_set:message.MsgTaskConditionInfo.argument_1)
}

// required int32 argument_2 = 3;
inline bool MsgTaskConditionInfo::has_argument_2() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void MsgTaskConditionInfo::set_has_argument_2() {
  _has_bits_[0] |= 0x00000004u;
}
inline void MsgTaskConditionInfo::clear_has_argument_2() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void MsgTaskConditionInfo::clear_argument_2() {
  argument_2_ = 0;
  clear_has_argument_2();
}
inline ::google::protobuf::int32 MsgTaskConditionInfo::argument_2() const {
  // @@protoc_insertion_point(field_get:message.MsgTaskConditionInfo.argument_2)
  return argument_2_;
}
inline void MsgTaskConditionInfo::set_argument_2(::google::protobuf::int32 value) {
  set_has_argument_2();
  argument_2_ = value;
  // @@protoc_insertion_point(field_set:message.MsgTaskConditionInfo.argument_2)
}

// -------------------------------------------------------------------

// MsgTaskConfigInfo

// required int32 taskID = 1;
inline bool MsgTaskConfigInfo::has_taskid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MsgTaskConfigInfo::set_has_taskid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MsgTaskConfigInfo::clear_has_taskid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MsgTaskConfigInfo::clear_taskid() {
  taskid_ = 0;
  clear_has_taskid();
}
inline ::google::protobuf::int32 MsgTaskConfigInfo::taskid() const {
  // @@protoc_insertion_point(field_get:message.MsgTaskConfigInfo.taskID)
  return taskid_;
}
inline void MsgTaskConfigInfo::set_taskid(::google::protobuf::int32 value) {
  set_has_taskid();
  taskid_ = value;
  // @@protoc_insertion_point(field_set:message.MsgTaskConfigInfo.taskID)
}

// repeated .message.MsgTaskConditionInfo task_condition = 2;
inline int MsgTaskConfigInfo::task_condition_size() const {
  return task_condition_.size();
}
inline void MsgTaskConfigInfo::clear_task_condition() {
  task_condition_.Clear();
}
inline const ::message::MsgTaskConditionInfo& MsgTaskConfigInfo::task_condition(int index) const {
  // @@protoc_insertion_point(field_get:message.MsgTaskConfigInfo.task_condition)
  return task_condition_.Get(index);
}
inline ::message::MsgTaskConditionInfo* MsgTaskConfigInfo::mutable_task_condition(int index) {
  // @@protoc_insertion_point(field_mutable:message.MsgTaskConfigInfo.task_condition)
  return task_condition_.Mutable(index);
}
inline ::message::MsgTaskConditionInfo* MsgTaskConfigInfo::add_task_condition() {
  // @@protoc_insertion_point(field_add:message.MsgTaskConfigInfo.task_condition)
  return task_condition_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::message::MsgTaskConditionInfo >&
MsgTaskConfigInfo::task_condition() const {
  // @@protoc_insertion_point(field_list:message.MsgTaskConfigInfo.task_condition)
  return task_condition_;
}
inline ::google::protobuf::RepeatedPtrField< ::message::MsgTaskConditionInfo >*
MsgTaskConfigInfo::mutable_task_condition() {
  // @@protoc_insertion_point(field_mutable_list:message.MsgTaskConfigInfo.task_condition)
  return &task_condition_;
}

// required int32 require_time = 3;
inline bool MsgTaskConfigInfo::has_require_time() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void MsgTaskConfigInfo::set_has_require_time() {
  _has_bits_[0] |= 0x00000004u;
}
inline void MsgTaskConfigInfo::clear_has_require_time() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void MsgTaskConfigInfo::clear_require_time() {
  require_time_ = 0;
  clear_has_require_time();
}
inline ::google::protobuf::int32 MsgTaskConfigInfo::require_time() const {
  // @@protoc_insertion_point(field_get:message.MsgTaskConfigInfo.require_time)
  return require_time_;
}
inline void MsgTaskConfigInfo::set_require_time(::google::protobuf::int32 value) {
  set_has_require_time();
  require_time_ = value;
  // @@protoc_insertion_point(field_set:message.MsgTaskConfigInfo.require_time)
}

// required int32 require_unlock_chapter = 4;
inline bool MsgTaskConfigInfo::has_require_unlock_chapter() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void MsgTaskConfigInfo::set_has_require_unlock_chapter() {
  _has_bits_[0] |= 0x00000008u;
}
inline void MsgTaskConfigInfo::clear_has_require_unlock_chapter() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void MsgTaskConfigInfo::clear_require_unlock_chapter() {
  require_unlock_chapter_ = 0;
  clear_has_require_unlock_chapter();
}
inline ::google::protobuf::int32 MsgTaskConfigInfo::require_unlock_chapter() const {
  // @@protoc_insertion_point(field_get:message.MsgTaskConfigInfo.require_unlock_chapter)
  return require_unlock_chapter_;
}
inline void MsgTaskConfigInfo::set_require_unlock_chapter(::google::protobuf::int32 value) {
  set_has_require_unlock_chapter();
  require_unlock_chapter_ = value;
  // @@protoc_insertion_point(field_set:message.MsgTaskConfigInfo.require_unlock_chapter)
}

// required int32 require_unlock_section = 5;
inline bool MsgTaskConfigInfo::has_require_unlock_section() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void MsgTaskConfigInfo::set_has_require_unlock_section() {
  _has_bits_[0] |= 0x00000010u;
}
inline void MsgTaskConfigInfo::clear_has_require_unlock_section() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void MsgTaskConfigInfo::clear_require_unlock_section() {
  require_unlock_section_ = 0;
  clear_has_require_unlock_section();
}
inline ::google::protobuf::int32 MsgTaskConfigInfo::require_unlock_section() const {
  // @@protoc_insertion_point(field_get:message.MsgTaskConfigInfo.require_unlock_section)
  return require_unlock_section_;
}
inline void MsgTaskConfigInfo::set_require_unlock_section(::google::protobuf::int32 value) {
  set_has_require_unlock_section();
  require_unlock_section_ = value;
  // @@protoc_insertion_point(field_set:message.MsgTaskConfigInfo.require_unlock_section)
}

// required int32 require_unlock_complete_task_count = 6;
inline bool MsgTaskConfigInfo::has_require_unlock_complete_task_count() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void MsgTaskConfigInfo::set_has_require_unlock_complete_task_count() {
  _has_bits_[0] |= 0x00000020u;
}
inline void MsgTaskConfigInfo::clear_has_require_unlock_complete_task_count() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void MsgTaskConfigInfo::clear_require_unlock_complete_task_count() {
  require_unlock_complete_task_count_ = 0;
  clear_has_require_unlock_complete_task_count();
}
inline ::google::protobuf::int32 MsgTaskConfigInfo::require_unlock_complete_task_count() const {
  // @@protoc_insertion_point(field_get:message.MsgTaskConfigInfo.require_unlock_complete_task_count)
  return require_unlock_complete_task_count_;
}
inline void MsgTaskConfigInfo::set_require_unlock_complete_task_count(::google::protobuf::int32 value) {
  set_has_require_unlock_complete_task_count();
  require_unlock_complete_task_count_ = value;
  // @@protoc_insertion_point(field_set:message.MsgTaskConfigInfo.require_unlock_complete_task_count)
}

// required int32 gift_gold = 7;
inline bool MsgTaskConfigInfo::has_gift_gold() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void MsgTaskConfigInfo::set_has_gift_gold() {
  _has_bits_[0] |= 0x00000040u;
}
inline void MsgTaskConfigInfo::clear_has_gift_gold() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void MsgTaskConfigInfo::clear_gift_gold() {
  gift_gold_ = 0;
  clear_has_gift_gold();
}
inline ::google::protobuf::int32 MsgTaskConfigInfo::gift_gold() const {
  // @@protoc_insertion_point(field_get:message.MsgTaskConfigInfo.gift_gold)
  return gift_gold_;
}
inline void MsgTaskConfigInfo::set_gift_gold(::google::protobuf::int32 value) {
  set_has_gift_gold();
  gift_gold_ = value;
  // @@protoc_insertion_point(field_set:message.MsgTaskConfigInfo.gift_gold)
}

// required string describe = 8;
inline bool MsgTaskConfigInfo::has_describe() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void MsgTaskConfigInfo::set_has_describe() {
  _has_bits_[0] |= 0x00000080u;
}
inline void MsgTaskConfigInfo::clear_has_describe() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void MsgTaskConfigInfo::clear_describe() {
  describe_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_describe();
}
inline const ::std::string& MsgTaskConfigInfo::describe() const {
  // @@protoc_insertion_point(field_get:message.MsgTaskConfigInfo.describe)
  return describe_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void MsgTaskConfigInfo::set_describe(const ::std::string& value) {
  set_has_describe();
  describe_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:message.MsgTaskConfigInfo.describe)
}
inline void MsgTaskConfigInfo::set_describe(const char* value) {
  set_has_describe();
  describe_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:message.MsgTaskConfigInfo.describe)
}
inline void MsgTaskConfigInfo::set_describe(const char* value, size_t size) {
  set_has_describe();
  describe_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:message.MsgTaskConfigInfo.describe)
}
inline ::std::string* MsgTaskConfigInfo::mutable_describe() {
  set_has_describe();
  // @@protoc_insertion_point(field_mutable:message.MsgTaskConfigInfo.describe)
  return describe_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* MsgTaskConfigInfo::release_describe() {
  clear_has_describe();
  return describe_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void MsgTaskConfigInfo::set_allocated_describe(::std::string* describe) {
  if (describe != NULL) {
    set_has_describe();
  } else {
    clear_has_describe();
  }
  describe_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), describe);
  // @@protoc_insertion_point(field_set_allocated:message.MsgTaskConfigInfo.describe)
}

// -------------------------------------------------------------------

// MsgShopConfigInfo

// required int32 grid_id = 1;
inline bool MsgShopConfigInfo::has_grid_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MsgShopConfigInfo::set_has_grid_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MsgShopConfigInfo::clear_has_grid_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MsgShopConfigInfo::clear_grid_id() {
  grid_id_ = 0;
  clear_has_grid_id();
}
inline ::google::protobuf::int32 MsgShopConfigInfo::grid_id() const {
  // @@protoc_insertion_point(field_get:message.MsgShopConfigInfo.grid_id)
  return grid_id_;
}
inline void MsgShopConfigInfo::set_grid_id(::google::protobuf::int32 value) {
  set_has_grid_id();
  grid_id_ = value;
  // @@protoc_insertion_point(field_set:message.MsgShopConfigInfo.grid_id)
}

// required int32 hero_id = 2;
inline bool MsgShopConfigInfo::has_hero_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MsgShopConfigInfo::set_has_hero_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MsgShopConfigInfo::clear_has_hero_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MsgShopConfigInfo::clear_hero_id() {
  hero_id_ = 0;
  clear_has_hero_id();
}
inline ::google::protobuf::int32 MsgShopConfigInfo::hero_id() const {
  // @@protoc_insertion_point(field_get:message.MsgShopConfigInfo.hero_id)
  return hero_id_;
}
inline void MsgShopConfigInfo::set_hero_id(::google::protobuf::int32 value) {
  set_has_hero_id();
  hero_id_ = value;
  // @@protoc_insertion_point(field_set:message.MsgShopConfigInfo.hero_id)
}

// required int32 require_gold = 3;
inline bool MsgShopConfigInfo::has_require_gold() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void MsgShopConfigInfo::set_has_require_gold() {
  _has_bits_[0] |= 0x00000004u;
}
inline void MsgShopConfigInfo::clear_has_require_gold() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void MsgShopConfigInfo::clear_require_gold() {
  require_gold_ = 0;
  clear_has_require_gold();
}
inline ::google::protobuf::int32 MsgShopConfigInfo::require_gold() const {
  // @@protoc_insertion_point(field_get:message.MsgShopConfigInfo.require_gold)
  return require_gold_;
}
inline void MsgShopConfigInfo::set_require_gold(::google::protobuf::int32 value) {
  set_has_require_gold();
  require_gold_ = value;
  // @@protoc_insertion_point(field_set:message.MsgShopConfigInfo.require_gold)
}

// required int32 cheape_gold = 4;
inline bool MsgShopConfigInfo::has_cheape_gold() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void MsgShopConfigInfo::set_has_cheape_gold() {
  _has_bits_[0] |= 0x00000008u;
}
inline void MsgShopConfigInfo::clear_has_cheape_gold() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void MsgShopConfigInfo::clear_cheape_gold() {
  cheape_gold_ = 0;
  clear_has_cheape_gold();
}
inline ::google::protobuf::int32 MsgShopConfigInfo::cheape_gold() const {
  // @@protoc_insertion_point(field_get:message.MsgShopConfigInfo.cheape_gold)
  return cheape_gold_;
}
inline void MsgShopConfigInfo::set_cheape_gold(::google::protobuf::int32 value) {
  set_has_cheape_gold();
  cheape_gold_ = value;
  // @@protoc_insertion_point(field_set:message.MsgShopConfigInfo.cheape_gold)
}

// -------------------------------------------------------------------

// MsgTaskInfo

// required int32 TaskID = 1;
inline bool MsgTaskInfo::has_taskid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MsgTaskInfo::set_has_taskid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MsgTaskInfo::clear_has_taskid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MsgTaskInfo::clear_taskid() {
  taskid_ = 0;
  clear_has_taskid();
}
inline ::google::protobuf::int32 MsgTaskInfo::taskid() const {
  // @@protoc_insertion_point(field_get:message.MsgTaskInfo.TaskID)
  return taskid_;
}
inline void MsgTaskInfo::set_taskid(::google::protobuf::int32 value) {
  set_has_taskid();
  taskid_ = value;
  // @@protoc_insertion_point(field_set:message.MsgTaskInfo.TaskID)
}

// required int32 argument_1 = 2;
inline bool MsgTaskInfo::has_argument_1() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MsgTaskInfo::set_has_argument_1() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MsgTaskInfo::clear_has_argument_1() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MsgTaskInfo::clear_argument_1() {
  argument_1_ = 0;
  clear_has_argument_1();
}
inline ::google::protobuf::int32 MsgTaskInfo::argument_1() const {
  // @@protoc_insertion_point(field_get:message.MsgTaskInfo.argument_1)
  return argument_1_;
}
inline void MsgTaskInfo::set_argument_1(::google::protobuf::int32 value) {
  set_has_argument_1();
  argument_1_ = value;
  // @@protoc_insertion_point(field_set:message.MsgTaskInfo.argument_1)
}

// required int32 useTime = 3;
inline bool MsgTaskInfo::has_usetime() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void MsgTaskInfo::set_has_usetime() {
  _has_bits_[0] |= 0x00000004u;
}
inline void MsgTaskInfo::clear_has_usetime() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void MsgTaskInfo::clear_usetime() {
  usetime_ = 0;
  clear_has_usetime();
}
inline ::google::protobuf::int32 MsgTaskInfo::usetime() const {
  // @@protoc_insertion_point(field_get:message.MsgTaskInfo.useTime)
  return usetime_;
}
inline void MsgTaskInfo::set_usetime(::google::protobuf::int32 value) {
  set_has_usetime();
  usetime_ = value;
  // @@protoc_insertion_point(field_set:message.MsgTaskInfo.useTime)
}

// -------------------------------------------------------------------

// MsgChapterConfigInfo

// required int32 chapter_id = 1;
inline bool MsgChapterConfigInfo::has_chapter_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MsgChapterConfigInfo::set_has_chapter_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MsgChapterConfigInfo::clear_has_chapter_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MsgChapterConfigInfo::clear_chapter_id() {
  chapter_id_ = 0;
  clear_has_chapter_id();
}
inline ::google::protobuf::int32 MsgChapterConfigInfo::chapter_id() const {
  // @@protoc_insertion_point(field_get:message.MsgChapterConfigInfo.chapter_id)
  return chapter_id_;
}
inline void MsgChapterConfigInfo::set_chapter_id(::google::protobuf::int32 value) {
  set_has_chapter_id();
  chapter_id_ = value;
  // @@protoc_insertion_point(field_set:message.MsgChapterConfigInfo.chapter_id)
}

// required int32 required_chapter_id = 2;
inline bool MsgChapterConfigInfo::has_required_chapter_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MsgChapterConfigInfo::set_has_required_chapter_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MsgChapterConfigInfo::clear_has_required_chapter_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MsgChapterConfigInfo::clear_required_chapter_id() {
  required_chapter_id_ = 0;
  clear_has_required_chapter_id();
}
inline ::google::protobuf::int32 MsgChapterConfigInfo::required_chapter_id() const {
  // @@protoc_insertion_point(field_get:message.MsgChapterConfigInfo.required_chapter_id)
  return required_chapter_id_;
}
inline void MsgChapterConfigInfo::set_required_chapter_id(::google::protobuf::int32 value) {
  set_has_required_chapter_id();
  required_chapter_id_ = value;
  // @@protoc_insertion_point(field_set:message.MsgChapterConfigInfo.required_chapter_id)
}

// required int32 required_section_id = 3;
inline bool MsgChapterConfigInfo::has_required_section_id() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void MsgChapterConfigInfo::set_has_required_section_id() {
  _has_bits_[0] |= 0x00000004u;
}
inline void MsgChapterConfigInfo::clear_has_required_section_id() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void MsgChapterConfigInfo::clear_required_section_id() {
  required_section_id_ = 0;
  clear_has_required_section_id();
}
inline ::google::protobuf::int32 MsgChapterConfigInfo::required_section_id() const {
  // @@protoc_insertion_point(field_get:message.MsgChapterConfigInfo.required_section_id)
  return required_section_id_;
}
inline void MsgChapterConfigInfo::set_required_section_id(::google::protobuf::int32 value) {
  set_has_required_section_id();
  required_section_id_ = value;
  // @@protoc_insertion_point(field_set:message.MsgChapterConfigInfo.required_section_id)
}

// required int32 required_task_complete_count = 4;
inline bool MsgChapterConfigInfo::has_required_task_complete_count() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void MsgChapterConfigInfo::set_has_required_task_complete_count() {
  _has_bits_[0] |= 0x00000008u;
}
inline void MsgChapterConfigInfo::clear_has_required_task_complete_count() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void MsgChapterConfigInfo::clear_required_task_complete_count() {
  required_task_complete_count_ = 0;
  clear_has_required_task_complete_count();
}
inline ::google::protobuf::int32 MsgChapterConfigInfo::required_task_complete_count() const {
  // @@protoc_insertion_point(field_get:message.MsgChapterConfigInfo.required_task_complete_count)
  return required_task_complete_count_;
}
inline void MsgChapterConfigInfo::set_required_task_complete_count(::google::protobuf::int32 value) {
  set_has_required_task_complete_count();
  required_task_complete_count_ = value;
  // @@protoc_insertion_point(field_set:message.MsgChapterConfigInfo.required_task_complete_count)
}

// required int32 require_gold = 5;
inline bool MsgChapterConfigInfo::has_require_gold() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void MsgChapterConfigInfo::set_has_require_gold() {
  _has_bits_[0] |= 0x00000010u;
}
inline void MsgChapterConfigInfo::clear_has_require_gold() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void MsgChapterConfigInfo::clear_require_gold() {
  require_gold_ = 0;
  clear_has_require_gold();
}
inline ::google::protobuf::int32 MsgChapterConfigInfo::require_gold() const {
  // @@protoc_insertion_point(field_get:message.MsgChapterConfigInfo.require_gold)
  return require_gold_;
}
inline void MsgChapterConfigInfo::set_require_gold(::google::protobuf::int32 value) {
  set_has_require_gold();
  require_gold_ = value;
  // @@protoc_insertion_point(field_set:message.MsgChapterConfigInfo.require_gold)
}

// required int32 max_section_count = 6;
inline bool MsgChapterConfigInfo::has_max_section_count() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void MsgChapterConfigInfo::set_has_max_section_count() {
  _has_bits_[0] |= 0x00000020u;
}
inline void MsgChapterConfigInfo::clear_has_max_section_count() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void MsgChapterConfigInfo::clear_max_section_count() {
  max_section_count_ = 0;
  clear_has_max_section_count();
}
inline ::google::protobuf::int32 MsgChapterConfigInfo::max_section_count() const {
  // @@protoc_insertion_point(field_get:message.MsgChapterConfigInfo.max_section_count)
  return max_section_count_;
}
inline void MsgChapterConfigInfo::set_max_section_count(::google::protobuf::int32 value) {
  set_has_max_section_count();
  max_section_count_ = value;
  // @@protoc_insertion_point(field_set:message.MsgChapterConfigInfo.max_section_count)
}

// -------------------------------------------------------------------

// MsgGoldShopConfigInfo

// required int32 id = 1;
inline bool MsgGoldShopConfigInfo::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MsgGoldShopConfigInfo::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MsgGoldShopConfigInfo::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MsgGoldShopConfigInfo::clear_id() {
  id_ = 0;
  clear_has_id();
}
inline ::google::protobuf::int32 MsgGoldShopConfigInfo::id() const {
  // @@protoc_insertion_point(field_get:message.MsgGoldShopConfigInfo.id)
  return id_;
}
inline void MsgGoldShopConfigInfo::set_id(::google::protobuf::int32 value) {
  set_has_id();
  id_ = value;
  // @@protoc_insertion_point(field_set:message.MsgGoldShopConfigInfo.id)
}

// required int32 resource_id = 2;
inline bool MsgGoldShopConfigInfo::has_resource_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MsgGoldShopConfigInfo::set_has_resource_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MsgGoldShopConfigInfo::clear_has_resource_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MsgGoldShopConfigInfo::clear_resource_id() {
  resource_id_ = 0;
  clear_has_resource_id();
}
inline ::google::protobuf::int32 MsgGoldShopConfigInfo::resource_id() const {
  // @@protoc_insertion_point(field_get:message.MsgGoldShopConfigInfo.resource_id)
  return resource_id_;
}
inline void MsgGoldShopConfigInfo::set_resource_id(::google::protobuf::int32 value) {
  set_has_resource_id();
  resource_id_ = value;
  // @@protoc_insertion_point(field_set:message.MsgGoldShopConfigInfo.resource_id)
}

// required int32 gold = 3;
inline bool MsgGoldShopConfigInfo::has_gold() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void MsgGoldShopConfigInfo::set_has_gold() {
  _has_bits_[0] |= 0x00000004u;
}
inline void MsgGoldShopConfigInfo::clear_has_gold() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void MsgGoldShopConfigInfo::clear_gold() {
  gold_ = 0;
  clear_has_gold();
}
inline ::google::protobuf::int32 MsgGoldShopConfigInfo::gold() const {
  // @@protoc_insertion_point(field_get:message.MsgGoldShopConfigInfo.gold)
  return gold_;
}
inline void MsgGoldShopConfigInfo::set_gold(::google::protobuf::int32 value) {
  set_has_gold();
  gold_ = value;
  // @@protoc_insertion_point(field_set:message.MsgGoldShopConfigInfo.gold)
}

// required float money = 4;
inline bool MsgGoldShopConfigInfo::has_money() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void MsgGoldShopConfigInfo::set_has_money() {
  _has_bits_[0] |= 0x00000008u;
}
inline void MsgGoldShopConfigInfo::clear_has_money() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void MsgGoldShopConfigInfo::clear_money() {
  money_ = 0;
  clear_has_money();
}
inline float MsgGoldShopConfigInfo::money() const {
  // @@protoc_insertion_point(field_get:message.MsgGoldShopConfigInfo.money)
  return money_;
}
inline void MsgGoldShopConfigInfo::set_money(float value) {
  set_has_money();
  money_ = value;
  // @@protoc_insertion_point(field_set:message.MsgGoldShopConfigInfo.money)
}

// required string describe = 5;
inline bool MsgGoldShopConfigInfo::has_describe() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void MsgGoldShopConfigInfo::set_has_describe() {
  _has_bits_[0] |= 0x00000010u;
}
inline void MsgGoldShopConfigInfo::clear_has_describe() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void MsgGoldShopConfigInfo::clear_describe() {
  describe_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_describe();
}
inline const ::std::string& MsgGoldShopConfigInfo::describe() const {
  // @@protoc_insertion_point(field_get:message.MsgGoldShopConfigInfo.describe)
  return describe_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void MsgGoldShopConfigInfo::set_describe(const ::std::string& value) {
  set_has_describe();
  describe_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:message.MsgGoldShopConfigInfo.describe)
}
inline void MsgGoldShopConfigInfo::set_describe(const char* value) {
  set_has_describe();
  describe_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:message.MsgGoldShopConfigInfo.describe)
}
inline void MsgGoldShopConfigInfo::set_describe(const char* value, size_t size) {
  set_has_describe();
  describe_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:message.MsgGoldShopConfigInfo.describe)
}
inline ::std::string* MsgGoldShopConfigInfo::mutable_describe() {
  set_has_describe();
  // @@protoc_insertion_point(field_mutable:message.MsgGoldShopConfigInfo.describe)
  return describe_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* MsgGoldShopConfigInfo::release_describe() {
  clear_has_describe();
  return describe_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void MsgGoldShopConfigInfo::set_allocated_describe(::std::string* describe) {
  if (describe != NULL) {
    set_has_describe();
  } else {
    clear_has_describe();
  }
  describe_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), describe);
  // @@protoc_insertion_point(field_set_allocated:message.MsgGoldShopConfigInfo.describe)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace message

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::message::SubType> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::message::SubType>() {
  return ::message::SubType_descriptor();
}
template <> struct is_proto_enum< ::message::TaskType> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::message::TaskType>() {
  return ::message::TaskType_descriptor();
}

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_common_2eproto__INCLUDED
